apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: siddhikhapare/frontend:latest
        imagePullPolicy: Always
        env:
        - name: API_URL
          value: https://demo.ksiddhiapphub.org
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "350Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"